### ISSUE TITLE
GUI for Clo plug-in

### ISSUE THREAD

**Issue by NicolasSocquetJuglard** [EnhanceThatComputer/CLO3D-Auto-Render-Plugin-Releases#1]
Hi, I need to create a Clo3D plug-in but don't know how to create the kind of GUI you did with your plug-in. Is there a way to access your source code or to get your method/libraries used to create those GUIs ? Thanks !

**Comment by geekbeard** [comment]
Hi @NicolasSocquetJuglard ! Sorry for the late reply. Please reach out to us on: zoomin@enhancethat.fashion and we can chat there about this:)
